<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSZpOsHa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSZpOsHa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSZpOsHa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSZpOsHa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSZpOsHa\App_KernelDevDebugContainer([
    'container.build_hash' => 'SZpOsHa',
    'container.build_id' => '33698eb0',
    'container.build_time' => 1686510749,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSZpOsHa');
