<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmrDHx7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmrDHx7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmrDHx7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmrDHx7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLmrDHx7\App_KernelDevDebugContainer([
    'container.build_hash' => 'LmrDHx7',
    'container.build_id' => '8cb67ea0',
    'container.build_time' => 1686647479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmrDHx7');
