<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKMDWeBw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKMDWeBw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKMDWeBw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKMDWeBw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKMDWeBw\App_KernelDevDebugContainer([
    'container.build_hash' => 'KMDWeBw',
    'container.build_id' => 'fbcbb291',
    'container.build_time' => 1686582940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKMDWeBw');
