<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_api_categories_browse' => [[], ['_controller' => 'App\\Controller\\Api\\CategoryController::browse'], [], [['text', '/api/categories']], [], [], []],
    'app_api_categories_read' => [['id'], ['_controller' => 'App\\Controller\\Api\\CategoryController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/categories']], [], [], []],
    'app_api_drinks_browse' => [[], ['_controller' => 'App\\Controller\\Api\\DrinkController::browse'], [], [['text', '/api/drinks']], [], [], []],
    'app_api_drinks_read' => [['id'], ['_controller' => 'App\\Controller\\Api\\DrinkController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/drinks']], [], [], []],
    'app_api_eats_browse' => [[], ['_controller' => 'App\\Controller\\Api\\EatController::browse'], [], [['text', '/api/eats']], [], [], []],
    'app_api_eats_read' => [['id'], ['_controller' => 'App\\Controller\\Api\\EatController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/eats']], [], [], []],
    'app_api_menus_browse' => [[], ['_controller' => 'App\\Controller\\Api\\MenuController::browse'], [], [['text', '/api/menus']], [], [], []],
    'app_api_menus_read' => [['id'], ['_controller' => 'App\\Controller\\Api\\MenuController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/menus']], [], [], []],
    'app_api_restaurants_browse' => [[], ['_controller' => 'App\\Controller\\Api\\RestaurantController::browse'], [], [['text', '/api/restaurants']], [], [], []],
    'app_api_restaurants_read' => [['id'], ['_controller' => 'App\\Controller\\Api\\RestaurantController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/restaurants']], [], [], []],
    'app_api_movie_browse' => [[], ['_controller' => 'App\\Controller\\Api\\MovieController::browse'], [], [['text', '/api/movies']], [], [], []],
    'app_api_movie_read' => [['id'], ['_controller' => 'App\\Controller\\Api\\MovieController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/movies']], [], [], []],
    'app_api_movie_add' => [[], ['_controller' => 'App\\Controller\\Api\\MovieController::add'], [], [['text', '/api/movies']], [], [], []],
    'app_api_users_browse' => [[], ['_controller' => 'App\\Controller\\Api\\UserController::browse'], [], [['text', '/api/users']], [], [], []],
    'app_api_users_read' => [['id'], ['_controller' => 'App\\Controller\\Api\\UserController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/users']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
